export const CREATE_POST = 'POST/CREATE_POST';
export const FETCH_POSTS = 'POST/FETCH_POSTS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const ADD_ERROR = 'APP/ADD_ERROR';
export const CLEAR_ERRORS = 'APP/CLEAR_ERRORS';